/* Generated By:JJTree: Do not edit this line. ASTFunc.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import Model.Function;
import Exceptions.FunctionAlreadyDefinedException;

public class ASTFunc extends SimpleNode {
  public ASTFunc(int id) {
    super(id);
  }

  public ASTFunc(Hudder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HudderVisitor visitor, Object data) {
    // Get the Parameter list and find out how many children it has
    ASTParamList paramList = (ASTParamList) this.jjtGetChild(0);
    int paramCount = paramList.jjtGetNumChildren();

    // Has this function been defined?
    if(Hudder.functions.containsKey(this.value)) 
    {
      Function function = Hudder.functions.get(this.value);

      if(function.paramCount == paramCount) {
        throw new FunctionAlreadyDefinedException(this.value.toString());
      }
    } 
    else 
    {
      Function function = new Function();
      function.name = this.value.toString();
      function.paramCount = paramCount;

      Hudder.functions.put(function.name, function);
    }



    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=543174fc59cbf67bd9b258daedff9900 (do not edit this line) */
