/* Generated By:JJTree: Do not edit this line. ASTFunc.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import Model.Function;
import Exceptions.FunctionAlreadyDefinedException;

public class ASTFunc extends SimpleNode {
  public ASTFunc(int id) {
    super(id);
  }

  public ASTFunc(Hudder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HudderVisitor visitor, Object data) {
    // Has this function been defined?
    if(Hudder.functions.containsKey(this.value.toString())) {
      throw new FunctionAlreadyDefinedException(this.value.toString());
    } else {
      Function function = new Function();
      function.name = this.value.toString();
      function.numberOfParameters = 0;
      System.out.println(function.name + function.numberOfParameters);

      Hudder.functions.put(function.name, function);
    }



    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=543174fc59cbf67bd9b258daedff9900 (do not edit this line) */
