/* Generated By:JJTree: Do not edit this line. ASTParamListCall.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParamListCall extends SimpleNode {
  public ASTParamListCall(int id) {
    super(id);
  }

  public ASTParamListCall(Hudder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HudderVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c7ebb36bd60db0364758b4170cf36af2 (do not edit this line) */
