/* Generated By:JavaCC: Do not edit this line. HudderTreeConstants.java Version 6.0_1 */
public interface HudderTreeConstants
{
  public int JJTHUDDER = 0;
  public int JJTVOID = 1;
  public int JJTFUNC = 2;
  public int JJTPARAMLIST = 3;
  public int JJTPROGBLOCK = 4;


  public String[] jjtNodeName = {
    "Hudder",
    "void",
    "Func",
    "ParamList",
    "ProgBlock",
  };
}
/* JavaCC - OriginalChecksum=8b22154dad6a5a5b6c898d2d1279db1f (do not edit this line) */
