/* Generated By:JavaCC: Do not edit this line. HudderConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HudderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FUN = 6;
  /** RegularExpression Id. */
  int HANDBACK = 7;
  /** RegularExpression Id. */
  int REPEAT = 8;
  /** RegularExpression Id. */
  int UNTIL = 9;
  /** RegularExpression Id. */
  int WHENEVER = 10;
  /** RegularExpression Id. */
  int DO = 11;
  /** RegularExpression Id. */
  int OTHERWISE = 12;
  /** RegularExpression Id. */
  int START = 13;
  /** RegularExpression Id. */
  int STOP = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int OR = 16;
  /** RegularExpression Id. */
  int VAR = 17;
  /** RegularExpression Id. */
  int OUTPUT = 18;
  /** RegularExpression Id. */
  int IDENTIFIER = 19;
  /** RegularExpression Id. */
  int STRING = 20;
  /** RegularExpression Id. */
  int NUMBER = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int MULT = 24;
  /** RegularExpression Id. */
  int DIV = 25;
  /** RegularExpression Id. */
  int ASSIGNMENT = 26;
  /** RegularExpression Id. */
  int EQUAL = 27;
  /** RegularExpression Id. */
  int NOT_EQUAL = 28;
  /** RegularExpression Id. */
  int GREATER = 29;
  /** RegularExpression Id. */
  int LESS = 30;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 31;
  /** RegularExpression Id. */
  int LESS_EQUAL = 32;
  /** RegularExpression Id. */
  int O_PAR = 33;
  /** RegularExpression Id. */
  int C_PAR = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int SEMI_COLON = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"|=.*=|\"",
    "\"fun\"",
    "\"handback\"",
    "\"repeat\"",
    "\"until\"",
    "\"whenever\"",
    "\"do\"",
    "\"otherwise\"",
    "\"start\"",
    "\"stop\"",
    "\"and\"",
    "\"or\"",
    "\"var\"",
    "\"output\"",
    "<IDENTIFIER>",
    "\"\\\".*\\\"\"",
    "<NUMBER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\":=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"(\"",
    "\")\"",
    "\"\\\'\"",
    "\";\"",
  };

}
