/* Generated By:JavaCC: Do not edit this line. HudderConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HudderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FUN = 8;
  /** RegularExpression Id. */
  int HANDBACK = 9;
  /** RegularExpression Id. */
  int REPEAT = 10;
  /** RegularExpression Id. */
  int UNTIL = 11;
  /** RegularExpression Id. */
  int WHENEVER = 12;
  /** RegularExpression Id. */
  int DO = 13;
  /** RegularExpression Id. */
  int OTHERWISE = 14;
  /** RegularExpression Id. */
  int START = 15;
  /** RegularExpression Id. */
  int STOP = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int VAR = 19;
  /** RegularExpression Id. */
  int OUTPUT = 20;
  /** RegularExpression Id. */
  int IDENTIFIER = 21;
  /** RegularExpression Id. */
  int STRING = 22;
  /** RegularExpression Id. */
  int NUMBER = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int MINUS = 25;
  /** RegularExpression Id. */
  int MULT = 26;
  /** RegularExpression Id. */
  int DIV = 27;
  /** RegularExpression Id. */
  int ASSIGNMENT = 28;
  /** RegularExpression Id. */
  int EQUAL = 29;
  /** RegularExpression Id. */
  int NOT_EQUAL = 30;
  /** RegularExpression Id. */
  int GREATER = 31;
  /** RegularExpression Id. */
  int LESS = 32;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 33;
  /** RegularExpression Id. */
  int LESS_EQUAL = 34;
  /** RegularExpression Id. */
  int O_PAR = 35;
  /** RegularExpression Id. */
  int C_PAR = 36;
  /** RegularExpression Id. */
  int COMMA = 37;
  /** RegularExpression Id. */
  int SEMI_COLON = 38;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INSIDE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"|=\"",
    "\"=|\"",
    "<token of kind 7>",
    "\"fun\"",
    "\"handback\"",
    "\"repeat\"",
    "\"until\"",
    "\"whenever\"",
    "\"do\"",
    "\"otherwise\"",
    "\"start\"",
    "\"stop\"",
    "\"and\"",
    "\"or\"",
    "\"var\"",
    "\"output\"",
    "<IDENTIFIER>",
    "\"\\\".*\\\"\"",
    "<NUMBER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\":=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
  };

}
