/* Generated By:JJTree: Do not edit this line. ASTFactor.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFactor extends SimpleNode {
  public ASTFactor(int id) {
    super(id);
  }

  public ASTFactor(Hudder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HudderVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=efa592c2b01c98e7629d8e984f64b9a3 (do not edit this line) */
