/* Generated By:JJTree: Do not edit this line. ASTHudder.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTHudder extends SimpleNode {
  public ASTHudder(int id) {
    super(id);
  }

  public ASTHudder(Hudder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HudderVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0c7b57e230044575a850a29340ec83a8 (do not edit this line) */
