/* Generated By:JJTree: Do not edit this line. ASTParam.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParam extends SimpleNode {
  public ASTParam(int id) {
    super(id);
  }

  public ASTParam(Hudder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HudderVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=72a0241707d6a5a5680d9970f80a81fe (do not edit this line) */
