/* Generated By:JavaCC: Do not edit this line. HudderVisitor.java Version 6.0_1 */
public interface HudderVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTHudder node, Object data);
  public Object visit(ASTFunc node, Object data);
  public Object visit(ASTParamList node, Object data);
  public Object visit(ASTProgBlock node, Object data);
}
/* JavaCC - OriginalChecksum=99d13e89a8261193a84dd35f8cf845df (do not edit this line) */
